title: A Revolutionary Idea
author: Bryan Hoang
email: bryan.c.hoang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A GitHub Page created from a tutorial.

# social links
twitter_username: your-twitter-handle
github_username:  Bryan-Hoang

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
